export const BACKGROUND_SOURCE_WIDTH = 2560;
export const BACKGROUND_SOURCE_HEIGHT = 1400;
export const DEFAULT_ACRYLIC_ANCHOR_Y = BACKGROUND_SOURCE_HEIGHT - 190;
export const DEFAULT_ACRYLIC_TOP_GAP = 36;
